[build]
  command = "npm run build"
  publish = "dist"

[functions]
  # If you add Netlify Functions, set the directory here (optional)
  directory = "netlify/functions"

[context.production.environment]
  # Example: environment variables can be set here for build time (but it's
  # recommended to set them in the Netlify UI instead)
  # GEMINI_API_KEY = ""

[redirects]
  # catch-all to support SPA routing (serve index.html for client routes)
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200